
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Job_Portal_development
  adapter: postgresql
  username: harry
  password: harry123
  host: localhost


  test:
  <<: *default
  database: Job_Portal_test
  
production:
  <<: *default
  database: Job_Portal_production
  username: harry
  password: harry123